### ISSUE TITLE
Year not exist

### ISSUE THREAD

**Issue by thelion371** [Almo7aya/anghamify#2]
Please add a year to your API for a specify object Id

thanks

**Comment by Almo7aya** [comment]
Hello,
I don't understand what you mean by 'year', can you please provide me with more details about your issue. :grin:

**Comment by thelion371** [comment]
I mean Year for song

**Comment by Almo7aya** [comment]
Again, I didn't understand you,
What the benefit of adding the year of a song?, how can this help Anghamify?

**Comment by thelion371** [comment]
Hi thanks for reply 

Every song in Anghami content year or you can said "date for release the song" and this very important to add it to your API

in other words "release year for song"

thanks

**Comment by Almo7aya** [comment]
Anghamify already writes the year of the song in the song's metadata, You can see the code below￼

And here an example of the year￼

Where did you find a song without a date?

**Comment by Almo7aya** [comment]
Anghamify already writes the year of the song in the song's metadata, You can see the code below

![jscode](https://i.imgur.com/iQGmgHJ.jpg)

And here an example of the year

![ssmusic](https://i.imgur.com/h09NfZD.jpg)

Where did you find a song without a date?

**Comment by thelion371** [comment]
I mean here and as your document 
when I request like this URL:
https://anghamify.cf/v1/data?objectid=153980&type=song 

I get 
{ id: ..
title: ...
artist:...
..etc }

I want here from you to add "YEAR" for this song

I hope now you understand what I mean

**Comment by Almo7aya** [comment]
Haaa, okay I finally understand you ☺, okay, I may add year to the response object soon,
Thank you.

**Comment by thelion371** [comment]
OK, perfect and I hope this thing doesn't go too long ❤️ 

thanks

**Comment by Almo7aya** [comment]
The 'year' has been added to the response object
